package com.ilargia.games.core;

import com.ilargia.games.components.Interactive;
import com.ilargia.games.components.GameBoard;
import com.ilargia.games.components.GameBoardElement;
import com.ilargia.games.components.Movable;
import com.ilargia.games.components.Destroy;
import com.ilargia.games.components.Position;
import com.ilargia.games.components.Asset;
import com.ilargia.games.components.View;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class CoreComponentIds {

	public static final int Interactive = 0;
	public static final int GameBoard = 1;
	public static final int GameBoardElement = 2;
	public static final int Movable = 3;
	public static final int Destroy = 6;
	public static final int Position = 7;
	public static final int Asset = 8;
	public static final int View = 10;
	public static final int totalComponents = 8;

	public static String[] componentNames() {
		return new String[]{"Interactive", "GameBoard", "GameBoardElement",
				"Movable", null, null, "Destroy", "Position", "Asset", null,
				"View", null, null, null, null, null, null, null, null};
	}

	public static Class[] componentTypes() {
		return new Class[]{Interactive.class, GameBoard.class,
				GameBoardElement.class, Movable.class, null, null,
				Destroy.class, Position.class, Asset.class, null, View.class,
				null, null, null, null, null, null, null, null};
	}
}