package com.ilargia.games.core;

import com.ilargia.games.components.Score;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class ScoreComponentIds {

	public static final int Score = 5;
	public static final int totalComponents = 1;

	public static String[] componentNames() {
		return new String[]{null, null, null, null, null, "Score", null, null,
				null, null, null, null};
	}

	public static Class[] componentTypes() {
		return new Class[]{null, null, null, null, null, Score.class, null,
				null, null, null, null, null};
	}
}